"""Constants module for configuration values."""

from .thresholds import (
    LARGE_OUTFLOW_THRESHOLD,
    HIGH_EXPENSE_RATIO_THRESHOLD,
    LOW_INFLOW_FREQUENCY_THRESHOLD,
    NSF_KEYWORDS,
)
from .prompts import (
    AI_SUMMARY_SYSTEM_PROMPT,
    AI_SUMMARY_USER_PROMPT,
)

__all__ = [
    "LARGE_OUTFLOW_THRESHOLD",
    "HIGH_EXPENSE_RATIO_THRESHOLD",
    "LOW_INFLOW_FREQUENCY_THRESHOLD",
    "NSF_KEYWORDS",
    "AI_SUMMARY_SYSTEM_PROMPT",
    "AI_SUMMARY_USER_PROMPT",
]
